services:
  app:
    build: .
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["streamlit", "run", "app/app.py", "--server.port", "8080"]

